#!/usr/bin/env node

let fs = require('fs')

let ti = require('../lib/texinfo')
let im = require('../lib/infomenu')

let markdown = fs.readFileSync(process.argv[2]).toString()
let menu = im.menu(markdown)
let texi = ti.markdown2texi(markdown, menu)

process.stdout.write(ti.render('file.md', texi))
