#!/usr/bin/env node

let fs = require('fs')

let md = require('../lib/markdown')
let im = require('../lib/infomenu')

let markdown = fs.readFileSync(process.argv[2]).toString()
let menu = im.menu(markdown)
let texi = md.markdown2texi(markdown, menu)

process.stdout.write(md.render('file.md', texi))
