#!/usr/bin/env node

let fs = require('fs')
let program = require('commander')
let util = require('util')

let ti = require('./lib/texinfo')
let im = require('./lib/infomenu')

program
    .version('2.0.0')
    .option('-t, --title <string>', 'Document title')
    .option('-a, --author <string>', 'Document author')
    .option('--info-cat <string>', 'Info category')
    .parse(process.argv)

let markdown = fs.readFileSync(program.args[0]).toString()

let menu = im.menu(markdown)
console.error(util.inspect(menu, {depth: null}))

let texi = ti.markdown2texi(markdown, menu)
process.stdout.write(ti.render('file.md', texi))
